### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by ali7d** [ali7d/Final_Year_Pjt#2]
Description

## TO-DO

- [x] Set up background
- [ ] Edit UI, Add some options
- [ ] Design an icon
- [ ] Add more features
- [ ] Fix the API limit generation
- [ ] Allow user to do multiple designs
